# Generated by Django 3.0.6 on 2020-09-29 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryID', models.AutoField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=100)),
                ('obtainedCategoryScore', models.IntegerField(default=0)),
                ('maxCategoryScore', models.IntegerField(default=0)),
                ('chained', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Catgory',
                'verbose_name_plural': 'Catgories',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('gameID', models.AutoField(primary_key=True, serialize=False)),
                ('gameName', models.CharField(max_length=100)),
                ('accessThroughTag', models.BooleanField(default=False)),
                ('accessTag', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('publicationDate', models.DateTimeField(auto_now_add=True)),
                ('lastChangedDate', models.DateTimeField(auto_now=True)),
                ('noDateNorTime', models.BooleanField(default=False)),
                ('startDateTime', models.DateTimeField(blank=True, default=None, null=True)),
                ('endDateTime', models.DateTimeField(blank=True, default=None, null=True)),
                ('open', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('minimalPlayerCount', models.IntegerField(default=0)),
                ('maximumPlayerCount', models.IntegerField(default=0)),
                ('numberOfPlayers', models.IntegerField(default=0)),
                ('generalText', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
            },
        ),
        migrations.CreateModel(
            name='GameItemLink',
            fields=[
                ('gameItemLinkID', models.AutoField(primary_key=True, serialize=False)),
                ('gameItemLinkName', models.CharField(max_length=100)),
                ('gameItemType', models.CharField(choices=[('TI', 'Text Item'), ('MC', 'Multiple Choice')], default='TI', max_length=2)),
                ('gameItemIDfk', models.IntegerField()),
                ('itemOrder', models.IntegerField(blank=True, default=0, null=True)),
                ('gameItemStateChangeMinInput', models.IntegerField(default=1)),
                ('gameItemStateGivenNInput', models.IntegerField(default=0)),
                ('gameItemStateGivenWrongNInput', models.IntegerField(default=0)),
                ('gameItemStateVisited', models.BooleanField(default=False)),
                ('gameItemStateCompleted', models.BooleanField(default=False)),
                ('gameItemContinueByGM', models.BooleanField(default=False)),
                ('gameItemMaxTime', models.TimeField(blank=True, default=None, null=True)),
                ('gameItemStartTime', models.DateTimeField(default=None, null=True)),
                ('maxScore', models.IntegerField(default=0)),
                ('obtainedScore', models.IntegerField(default=0)),
                ('faultPenalty', models.IntegerField(default=0)),
                ('maxNumAttempts', models.IntegerField(default=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Category')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game')),
                ('nextItem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.GameItemLink')),
            ],
            options={
                'verbose_name': 'GameItemLink',
                'verbose_name_plural': 'GameItemLinks',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='firstItem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firstItem', to='game.GameItemLink'),
        ),
        migrations.AddField(
            model_name='category',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game'),
        ),
    ]
