# Generated by Django 3.0.6 on 2020-10-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20201002_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameitemlink',
            name='gameItemStartTime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
