# Generated by Django 3.0.6 on 2020-10-04 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20201004_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='maximumPlayerCount',
        ),
        migrations.RemoveField(
            model_name='game',
            name='minimalPlayerCount',
        ),
        migrations.RemoveField(
            model_name='game',
            name='numberOfPlayers',
        ),
        migrations.RemoveField(
            model_name='gameitemlink',
            name='gameItemStateChangeMinInput',
        ),
    ]
