# Generated by Django 3.0.6 on 2020-10-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20201004_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameitemlink',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
